### ISSUE TITLE
Recomendação do Symfony com relação à Bundles

### ISSUE THREAD

**Issue by Luitame** [PHPcomRapadura/site-principal#10]
@dersonsena no [Symfony 4](https://symfony.com/4) não é mais recomendado organizar sua lógica de negócios usando **bundles**. A separação agora é recomendada ser feita usando **namespaces**. Inclusive, no começo dessa [doc sobre bundles fala isto](https://symfony.com/doc/current/bundles.html). Essa abordagem do Symfony foi com o intuito de simplificar as coisas, dissociar mais o código do framework e substituir alguns `conceitos do Symfony` pelos recursos padrão do PHP, no Symfony 4.1 foi descontinuada a notação **bundle** em favor da **notação regular do namespace do PHP**.

> **The Bundle System**
>
>Nas versões do Symfony anteriores a 4.0, foi recomendado organizar seu próprio código de aplicativo usando pacotes configuráveis. Isso não é mais recomendado e os pacotes só devem ser usados ​​para compartilhar códigos e recursos entre vários aplicativos.
>
>Um pacote é semelhante a um plugin em outro software, mas ainda melhor. Os principais recursos do framework Symfony são implementados com bundles (FrameworkBundle, SecurityBundle, DebugBundle, etc.). Eles também são usados para adicionar novos recursos em seu aplicativo por meio de bundles de terceiros.
>
> [Leia mais](https://symfony.com/doc/current/bundles.html)

Então, acredito que a gente deve rever [essa abordagem](https://github.com/PHPcomRapadura/site-principal/tree/d2be514be422b1c20ccb2160bb44ebcc49afb2c5/src/AdminBundle).

Nesses dois links a seguir, [Fabien](https://twitter.com/fabpot) o criador do [Symfony](https://symfony.com) também fala à respeito.

- http://fabien.potencier.org/symfony4-best-practices.html
- http://fabien.potencier.org/symfony4-monolith-vs-micro.html

Outro [link](https://symfony.com/blog/new-in-symfony-4-1-deprecated-the-bundle-notation) útil -> https://symfony.com/blog/new-in-symfony-4-1-deprecated-the-bundle-notation

**Comment by dersonsena** [comment]
Show de bola @Luitame ! Confesso que não sabia disso. Irei refatorar essa parte então e deixar tudo tinino =)

**Comment by dersonsena** [comment]
Refatorado ! =)
