### ISSUE TITLE
[ADMIN] - Autenticação

### ISSUE THREAD

**Issue by dersonsena** [PHPcomRapadura/site-principal#12]
### Definição
Implementação da autenticação dos administradores e moderadores do portal da comunidade. O usuário deverá entrar com seu **e-mail** e **senha** para ter acesso a área administrativa.

### Entity, Repository e Migration
Deve-se ser criada a Entity **Usuario**, seu Repository e Migration com as propriedades:

- `id`;
- `nome`: nome legível do usuário;
- `email`: e-mail para autenticação e envio de mensagens;
- `senha`: senha de acesso do usuário criptografada;
- `grupo`: campo de texto que representará o grupo de usuário. Possíveis valores: `ROLE_ADMIN`, `ROLE_MODERADOR`, `ROLE_REDATOR` e `ROLE_MEMBRO`  
- `avatar`: (OPCIONAL) campo para o nome da imagem que representa o avatar do usuário;
- `token`: (OPCIONAL) campo que representa o token para recuperação de senha;
- `sessao`: (OPCIONAL) campo que representa o hash de sessão do usuário autenticado;
- `status`: campo booleano que representa o status do usuário;
- `criado_em`: campo de data/hora que representa a data e hora de criação do registro;
- `criado_por`: ID do usuário que criou o registro;
- `atualizado_em`: (OPCIONAL) campo de data/hora que representa a data e hora da última atualização do registro;
- `removido_em`: (OPCIONAL) campo de data/hora que representa a data e hora da deleção do registro;
- `removido_por`: (OPCIONAL) ID do usuário que removeu/deletou o registro;

### Fixture
Deverá ser criado uma Fixture com um usuário com as informações abaixo:

- `id` = 1;
- `nome`: Administrador
- `email`: admin@phpcomrapadura.com.br
- `senha`: rapaduradopoder (senha criptografada!)
- `grupo`: ROLE_ADMIN
- `avatar`: `NULL`
- `status`: 1
- `criado_em`: `NOW()`

**Comment by Luitame** [comment]
banco em pt-BR? @dersonsena

**Comment by dersonsena** [comment]
@Luitame Sugeri ser em pt-BR porque todo o projeto, toda a documentação está em pt-BR e também por nosso projeto ser algo local.

**Comment by VinicSilva** [comment]
Os campos que estão com "(OPCIONAL)". Significa que são opcionais de preenchimento na table ou opcionais para a entidade?

**Comment by dersonsena** [comment]
@VinicSilva em ambos rsrsrsrs

**Comment by jholdy** [comment]
Concluida pra testes.

**Comment by dersonsena** [comment]
Show de bola hein @jholdy ! Faz uma PR para eu e nossa gerentona @alinechavessilva analisarmos ok ? Estamos aguardando :)

**Comment by alinechavessilva** [comment]
Me atrasei aqui, mas vou deixar meu comentário por que ainda pode ser mudado, seria interessante padronizar o nome das classes e atributos, ou tudo em português ou inglês
