### ISSUE TITLE
[ADMIN] - CRUD Patrocinadores e Apoiadores

### ISSUE THREAD

**Issue by dersonsena** [PHPcomRapadura/site-principal#22]
### Definição
Criar funcionalidades de Create, Read, Update e Delete dos Patrocinadores/Apoiadores da comunidade.

### Entity, Repository e Migration
Deve-se ser criada a Entity **Partner**, seu Repository e Migration com as propriedades:

- `id`;
- `name`: nome para o patrocinador/apoiador;
- `slug`: string com o slug do nome do patrocinador/apoiador;
- `image`: nome da imagem/logomarca do patrocinador/apoiador;
- `type`: flag que sinaliza se é um `patrocinador` ou um `apoiador`;
- `status`: campo booleano que representa o status do registro;
- `created_at`: campo de data/hora que representa a data e hora de criação do registro;
- `created_by`: ID do usuário que criou o registro;
- `updated_at`: (OPCIONAL) campo de data/hora que representa a data e hora da última atualização do registro;

**Comment by VinicSilva** [comment]
Vou iniciar essa atividade.

**Comment by dersonsena** [comment]
Show de bola @VinicSilva ! Qualquer coisa, só comentar aqui.

**Comment by Luitame** [comment]
@VinicSilva não esquece de seguir a [metodologia de versionament](https://danielkummer.github.io/git-flow-cheatsheet/index.pt_BR.html) adotada e commitar a cada alteração feita no arquivos do projeto.

**Comment by viniciuspereirafs** [comment]
Ta beleza. Se eu ficar com dúvidas a respeito do versionamento eu aviso.
