### ISSUE TITLE
Versionamento do projeto

### ISSUE THREAD

**Issue by Luitame** [PHPcomRapadura/site-principal#3]
Não vale todo commit ser na branch **master** né?! :) 
Que tal usar a abordagem do [**git-flow**](https://danielkummer.github.io/git-flow-cheatsheet/index.pt_BR.html) para tratar do versionamento semântico do projeto? Já que será uma obra feita a varias mãos. Acredito que seja uma boa abordagem. Vê esse [[link aqui]](https://danielkummer.github.io/git-flow-cheatsheet/index.pt_BR.html) para ver a doc em **pt-BR**.

> Se sinta à vontade pra dá uma buscada no [Youtube](http://youtube.com). E pra quem tem assinatura na School of Net [esse mini curso](https://www.schoolofnet.com/curso-git-flow-na-pratica-v2/) também é da hora!

**Comment by dersonsena** [comment]
Ótima iniciativa @Luitame ! Vou dá uma olhada nesse guia que você indicou! Nunca cheguei a usar o Git Flow, será um aprendizado para mim!

**Comment by dersonsena** [comment]
Recomendo esse vídeo falando sobre o GitFlow:

[https://www.youtube.com/watch?v=0L1zx7l6JSc](https://www.youtube.com/watch?v=0L1zx7l6JSc)

e também esse post aqui:

[https://medium.com/trainingcenter/utilizando-o-fluxo-git-flow-e63d5e0d5e04](https://medium.com/trainingcenter/utilizando-o-fluxo-git-flow-e63d5e0d5e04)
