### ISSUE TITLE
[ADMIN] - Refatoração das propriedades de Usuário

### ISSUE THREAD

**Issue by dersonsena** [PHPcomRapadura/site-principal#32]
Como foi convencionado há pouco tempo os nomes das tabelas/Entities e colunas/propriedades devem ser todas em inglês [VEJA MAIS DETALHES](/PHPcomRapadura/site-principal/blob/develop/docs/DATABASE.md).

### Entity, Repository e Migration
A Entity deve ser alterada para **User** com as propriedades:

- `id`;
- `name`: nome legível do usuário;
- `email`: e-mail para autenticação e envio de mensagens;
- `password`: senha de acesso do usuário criptografada;
- `roles`: campo de texto que representará o grupo de usuário ou papéis do usuário no sistema. Possíveis valores: `ROLE_ADMIN`, `ROLE_MODERADOR`, `ROLE_REDATOR` e `ROLE_MEMBRO`  
- `avatar`: (OPCIONAL) campo para o nome da imagem que representa o avatar do usuário;
- `token`: (OPCIONAL) campo que representa o token para recuperação de senha;
- `session_name`: (OPCIONAL) campo que representa o hash de sessão do usuário autenticado;
- `status`: campo booleano que representa o status do usuário;
- `created_at`: campo de data/hora que representa a data e hora de criação do registro;
- `created_by`: ID do usuário que criou o registro;
- `updated_at`: (OPCIONAL) campo de data/hora que representa a data e hora da última atualização do registro;
- `deleted_at`: (OPCIONAL) campo de data/hora que representa a data e hora da deleção do registro;
- `deleted_by`: (OPCIONAL) ID do usuário que removeu/deletou o registro;

**Comment by jholdy** [comment]
Ola gostaria de da uma opinião referente ao nome do campo group, acho que fica melhor se for roles. Oque acha?

**Comment by Luitame** [comment]
Concordo contigo @jholdy

**Comment by dersonsena** [comment]
Ótima sugestão Jholdy! Vou alterar agora o nome da coluna ;)

**Comment by ghost** [comment]
Olá outra coisa que reparei é que o nome da entity não deve ser User mais sim Users pois User é uma variável reservada do postgresql e isso pode atrapalhar futuras implementações.

**Comment by ghost** [comment]
Vou fazer essa atividade.

**Comment by dersonsena** [comment]
Show de Bola @jholdy ! Estou fazendo a #13 e a Entity já tem uma pequena dependência do Model Usuario.
