### ISSUE TITLE
Layout para Área Administrativa

### ISSUE THREAD

**Issue by dersonsena** [PHPcomRapadura/site-principal#7]
Estive pensando em colocar o [AdminLTE 2](https://adminlte.io/themes/AdminLTE/index2.html) como o layout para nossa área administrativa. Porém, como nosso intuito aqui é também aprender, pensei em colocar algum template semelhante, que seja **FREE** e com [Bootstrap 4](http://getbootstrap.com/).

Alguém sugere algum nesses moldes ?

**Comment by dersonsena** [comment]
Achei esse aqui, bem simples e direto ao ponto!

[https://startbootstrap.com/template-overviews/sb-admin-2/](https://startbootstrap.com/template-overviews/sb-admin-2/)

**Comment by wilcorrea** [comment]
Eu curto o gentelella. Cria um comentário para cada um e a galera vota com o :+1: .. o que acha @dersonsena ?

**Comment by Luitame** [comment]
Curti bastante esse **gentelella**

**Comment by Luitame** [comment]
@marcialwushu pela votação do ativos aqui o Gentelella já ganhou!

**Comment by marcialwushu** [comment]
@Luitame 
Verdade, mas esse Gentelella tem um layout bem legal.
O @dersonsena gostou do Sufee Admin da Colorlib, voto de chefe tem peso 2 ?

**Comment by Luitame** [comment]
@dersonsena acredito que não né!

**Comment by wilcorrea** [comment]
@marcialwushu chefe geralmente não serve pra nada.. só faz é raiva :1st_place_medal:

**Comment by dersonsena** [comment]
kkkkkkkk ! Vamo de **Gentella** então! Definido nosso template da Área de Administração!

**Comment by alinechavessilva** [comment]
Gostei desse - > https://bootstrapious.com/p/bootstrap-4-dashboard

**Comment by dersonsena** [comment]
@alinechavessilva .... como a gente abriu uma "votação" de 4 pessoas, a gente decidiu em por o **Gentella** =)

**Comment by wilcorrea** [comment]
Já era @alinechavessilva
